## 端口号 上下文路径
server:
  port: 8989
  servlet:
    context-path: /crm

## 数据源配置
spring:
  datasource:
    type: com.mchange.v2.c3p0.debug.AfterCloseLoggingComboPooledDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crm?useSSL=true&allowMultiQueries=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 1234
    ##freemarker
  freemarker:
    suffix: .ftl
    charset: UTF-8
    template-loader-path: classpath:/views/
    content-type: text/html

## mybatis配置
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.shsxt.crm.vo;com.shsxt.crm.query;com.shsxt.crm.dto;
  ##自定转化为驼峰
  configuration:
    map-underscore-to-camel-case: true

##分页插件
pagehelper:
  helper-dialect: mysql




